openapi: '3.0.2'
info:
  title: API Onboarding
  version: '1.0'
servers:
  - url: https://STD22091.com
paths:
  /students:
    get:
      summary: Récupérer les informations des étudiants
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema: 
                $ref:'#/components/schemas/Student'
        '500':
          description: Erreur interne du serveur
          content:
            text/plain:
              example: Une erreur est survenue
    post:
      summary: Ajouter un nouvel étudiant
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref:'#/components/schemas/Student'
      responses:
        '200':
          description: Succès
          content:
            application/json:
              example:
                message: Étudiant ajouté avec succès
        '500':
          description: Erreur interne du serveur
          content:
            text/plain:
              example: Une erreur est survenue
      components:
        schemas:
          Student:
          type: object
          properties:
            type: object
            properties: 
            id:
             type: integer
              format: int64
              example : 1
             name :
             type: string
              format: int64
              example: Tsinjo
                
            
              
