openapi: 3.0.2
info:
  title: API Onboarding
  version: '1.0'
servers:
  - url: https://STD22091.com
paths:
  /students:
    get:
      summary: Récupérer les informations des étudiants
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentInfo'
        '500':
          description: Erreur interne du serveur
          content:
            text/plain:
              example: Une erreur est survenue
    post:
      summary: Ajouter un nouvel étudiant
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewStudent'
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessMessage'
        '500':
          description: Erreur interne du serveur
          content:
            text/plain:
              example: Une erreur est survenue
components:
  schemas:
    StudentInfo:
      type: object
      properties:
        student_id:
          type: integer
        name:
          type: string
        age:
          type: integer
      example:
        student_id: 123
        name: John Doe
        age: 20

    NewStudent:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer

    SuccessMessage:
      type: object
      properties:
        message:
          type: string
      example:
        message: Étudiant ajouté avec succès
