openapi: 3.0.2
info:
  title: API Onboarding
  version: '1.0'
servers:
  - url: https://STD22091.com
paths:
  /students:
    get:
      summary: Récupérer les informations des étudiants
      tags:
        - Students
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentInfo'
        '500':
          description: Erreur interne du serveur
          content:
            text/plain:
              example: Une erreur est survenue
    post:
      summary: Ajouter un nouvel étudiant
      tags:
        - Students
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewStudent'
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessMessage'
        '500':
          description: Erreur interne du serveur
          content:
            text/plain:
              example: Une erreur est survenue
    put:
      summary: Mettre à jour les informations d'un étudiant
      tags:
        - Students
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentInfo'
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessMessage'
        '500':
          description: Erreur interne du serveur
          content:
            text/plain:
              example: Une erreur est survenue
    delete:
      summary: Supprimer un étudiant
      tags:
        - Students
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessMessage'
        '500':
          description: Erreur interne du serveur
          content:
            text/plain:
              example: Une erreur est survenue

  /teachers:
    get:
      summary: Récupérer les informations des enseignants et des cours
      tags:
        - Teachers
      responses:
        '200':
          description: Succès
          content:
            application/json:
              example:
                - teacher_name: Tokimahery Ramarozaka
                  courses:
                    - course_name: Algorithmique
                      course_code: prog1
                      course_duration: 12 semaines
        '500':
          description: Erreur interne du serveur
          content:
            text/plain:
              example: Une erreur est survenue
    post:
      summary: Ajouter un nouvel enseignant avec des cours
      tags:
        - Teachers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTeacher'
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessMessage'
        '500':
          description: Erreur interne du serveur
          content:
            text/plain:
              example: Une erreur est survenue

components:
  schemas:
    StudentInfo:
      type: object
      properties:
        student_id:
          type: integer
        name:
          type: string
        age:
          type: integer
      example:
        student_id: 123
        name: John Doe
        age: 20

    NewStudent:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer

    SuccessMessage:
      type: object
      properties:
        message:
          type: string
      example:
        message: Opération réussie

    NewTeacher:
      type: object
      properties:
        teacher_name:
          type: string
        courses:
          type: array
          items:
            $ref: '#/components/schemas/Course'
      example:
        teacher_name: Tokimahery Ramarozaka
        courses:
          - course_name: Algorithmique
            course_code: prog1
            course_duration: 12 semaines

    Course:
      type: object
      properties:
        course_name:
          type: string
        course_code:
          type: string
        course_duration:
          type: string
      example:
        course_name: Algorithmique
        course_code: prog1
        course_duration: 12 semaines
